### ISSUE TITLE
從 google 進入時錯誤跳轉404

### ISSUE THREAD

**Issue by jd3main** [Limeishu/limeishu.org#8]
從 google 搜尋進入線上美術館任一幅畫的頁面，會在載入後跳轉到 404 頁面

**Comment by Aries0d0f** [comment]
抱歉，之前重設資料庫時導致畫作 id 都被一起重設，所以連結都不一樣了QQ，這只能等 Google 把我們的索引重設才能解決

> ```Solution``` 已提交新的 ```sitemap.xml``` 至 Google Search Console
